/*
 * MathParser.h
 *
 *  Created on: May 1, 2014
 *      Author: Michael Fong
 */

#ifndef MATHPARSER_H_
#define MATHPARSER_H_

#include "compile/parser/Parser.h"
#include "algorithm/event/dispatcher/EventDispatcher.h"
#include "cli/MetricsManager.h"

/**
 *
 * MathParser inherits from Parser and implements the concrete functionalities
 * for parsing a math expression generated by Bison and Flex.
 *
 * @since 0.1
 */
class MathParser: public Parsable, public EventDispatcher {
public:
	MathParser();

	virtual ~MathParser();

	virtual void parse(ASTNodePtr& root, std::string line);

	virtual void parse(std::ifstream inFile);

};

#endif /* MATHPARSER_H_ */
